version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: pg-register
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registerdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
