name: Deploy Auth Service 1.0

on:
  push:
    branches:
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd services/auth-service/EventZone/Backend/User-domain/auth-service || exit 1
          git pull origin QA
          docker build -t auth-backend .
          docker stop auth-backend || true
          docker rm auth-backend || true
          docker run -d -p 3002:3002 --name auth-backend auth-backend

          cd ../../../Frontend/User-domain/auth-frontend || exit 1
          git pull origin QA
          docker build -t auth-frontend .
          docker stop auth-frontend || true
          docker rm auth-frontend || true
          docker run -d -p 3003:3003 --name auth-frontend auth-frontend
        EOF
