name: Deploy Auth Service to EC2

on:
  push:
    branches:
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2 via SSH
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/services/auth-service
          
          docker stop auth-backend || true
          docker rm auth-backend || true
          docker rmi auth-backend || true
          
          docker stop auth-frontend || true
          docker rm auth-frontend || true
          docker rmi auth-frontend || true
          
          git pull origin main || true
          
          cd backend
          docker build -t auth-backend .
          docker run -d --name auth-backend -p 3002:3002 auth-backend
          
          cd ../frontend
          docker build -t auth-frontend .
          docker run -d --name auth-frontend -p 3003:3003 auth-frontend
        EOF
