name: Build & Deploy User Domain 8.0

on:
  push:
    branches:
      - QA
    paths:
      - 'Backend/User-domain/**'
      - 'Frontend-Domains/user-frontend/**'
      - '.github/workflows/User-domain.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build & Push Register Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/register-service:qa ./Backend/User-domain/register-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/register-service:qa

      - name: Build & Push Auth Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:qa ./Backend/User-domain/auth-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:qa

      - name: Build & Push User Profile Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-profile-service:qa ./Backend/User-domain/user-profile-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-profile-service:qa

      - name: Build & Push User Roles Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-roles-service:qa ./Backend/User-domain/user-roles-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-roles-service:qa

      - name: Build & Push Preferences Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/preferences-service:qa ./Backend/User-domain/preferences-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/preferences-service:qa

      - name: Build & Push Notifications Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/notifications-service:qa ./Backend/User-domain/notifications-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/notifications-service:qa

      - name: Build & Push User Activity Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-activity-service:qa ./Backend/User-domain/user-activity-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-activity-service:qa

      - name: Build & Push Login Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/login-service:qa ./Backend/User-domain/login-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/login-service:qa

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.EC2_USER }} || exit 1
            if [ ! -d "user-domain" ]; then
              git clone https://github.com/aalopezb/EventZone.git user-domain
            fi
            cd user-domain
            git checkout QA
            git pull origin QA

            docker-compose pull
            docker-compose up -d
