name: Deploy to EC2

on:
  push:
    branches:
      - QA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.EC2_USER }} || exit 1
            if [ ! -d "user-domain" ]; then
              git clone https://github.com/aalopezb/EventZone.git user-domain
            fi
            cd user-domain
            git pull origin main

            docker-compose down

            docker-compose build

          
            docker-compose up -d
